# Generated by Django 4.0.4 on 2022-05-17 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame', models.ImageField(upload_to='')),
                ('position', models.CharField(max_length=50)),
                ('timestamp', models.CharField(max_length=50)),
            ],
        ),
    ]
