# Generated by Django 4.0.4 on 2022-05-17 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='frame',
            field=models.CharField(max_length=50),
        ),
    ]
