# Generated by Django 4.0.4 on 2022-05-19 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera_api', '0002_alter_data_frame'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='name',
            field=models.CharField(default='nome', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='data',
            name='frame',
            field=models.ImageField(upload_to='images'),
        ),
    ]
