# Generated by Django 4.0.4 on 2022-05-26 09:49

import camera_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera_api', '0004_data_path_alter_data_frame'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='frame',
            field=models.ImageField(upload_to=camera_api.models.get_frame_path),
        ),
        migrations.AlterField(
            model_name='data',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
