# Generated by Django 4.0.4 on 2022-06-27 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera_api', '0005_alter_data_frame_alter_data_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='frame',
            field=models.CharField(max_length=100),
        ),
    ]
